### ISSUE TITLE
Getting tasks from some filters seems to return v1 task's scheme

### ISSUE THREAD

**Issue by thomaslombart** [Doist/todoist-api-typescript#145] opened 2022-09-21 06:36 UTC
## Bug description

I have a call that returns tasks with the v1 scheme when using a filter:

```js
const tasks = await todoist.getTasks({ filter: "today|overdue" })
```

As an example, the tasks do have a `labelIds` property instead of just `labels`.

I've tried it out with different filters and couldn't reproduce with all of them. Some seem to work, some others don't. For example: `view all` filter also returns the old scheme in my case.

## Expected behavior

Getting these tasks this way should return the v2 task's scheme.

## Is reproducible

Yes

## To reproduce

Make the following call:

```js
const tasks = await todoist.getTasks({ filter: "today|overdue" })
```

It should return the old task's scheme.

## Version information:

-   Package version: 2.0.3

**Comment by thomaslombart** [comment] 2022-09-21 06:45
After trying out many filters, it seems putting the filter between parenthesis does the trick: `(today|overdue)`

Not sure why this happens 🙂

**Comment by henningmu** [comment] 2022-09-22 12:16
Hey @thomaslombart, unfortunately, I'm unable to reproduce this :/ 
If it's not too much trouble, would you create a new Todoist account with a throw-away email, and if you can reproduce it on there share the API token with me through email (henning@doist.com)? You could also the email of the account you're experiencing this in with me through email. I can then ask our API team to look into this more deeply 👍

**Comment by henningmu** [comment] 2022-10-11 08:29
Discussed this via email, seemed to be a duplicate of #149 so can be closed now.

**Closed by henningmu** 2022-10-11 08:29 UTC
Labels: bug
