### ISSUE TITLE
getTasks with filter with emoji doesn't return correct result

### ISSUE THREAD

**Issue by dmitry-yudakov** [Doist/todoist-api-typescript#251] opened 2024-01-16 15:29 UTC
## Bug description

I have a label containing unicode emoji like 📌 and try to use it in filter. It works in Todoist UI but doesn't work when used from API and returns an empty result.

## Expected behaviour

I expect the behavior of getting task with a filter to be consistent between Todoist UI and the api.

## Is reproducible

Yes

## To reproduce

Have at least one task with label "📌".

```
api.getTasks({ filter: '@📌', lang: 'en' })
```

## Version information:

-   Package version: 3.0.1, 2.1.2

## Additional information

it might be related to #250 issue but I decided to open a new one just in case.

I'm trying to workaroud this somehow getting the unicode number for this emoji and use it like `\ud83d` but it doesn't have any visible effect. 

Can you suggest something I could do to workaround this on my side?

**Comment by henningmu** [comment] 2024-01-17 13:36
@dmitry-yudakov It's a related but not the same issue, so thank you for opening it. Again, I have forwarded it to our backend team so they can fix the root cause of this and will report back on any developments 👍

**Comment by henningmu** [comment] 2024-01-18 09:18
This will depend on how your users are using the app / SDK. One option might be to query by label directly:

```
api.getTasks({ label: '📌' })
```

**Comment by dmitry-yudakov** [comment] 2024-01-18 13:47
Unfortunately it has to be done using Todoist filters. I can only detect the emoji characters and alter the content of the filter string.

I tried replacing the emoji in the filter with different representations of its Unicode code so that `@📌` would be `@U+1F4CC` or `@\ud83d\udccc`, tried escaping it with `@\📌` as well but nothing helps.

**Comment by henningmu** [comment] 2024-01-22 12:26
@dmitry-yudakov our team is still working on a solution. In the meantime they suggested you could try replacing emoji with wildcards, but this doesn't work when there's no text to the label (e.g. emoji-only):

`@📌pinned` -> `@*pinned` could work 👍

**Comment by dmitry-yudakov** [comment] 2024-02-08 12:31
Hi @henningmu, does the backend team have any progress on this?

**Comment by henningmu** [comment] 2024-02-09 08:38
A fix is in progress, but since it's related to encoding it's a bit tougher to resolve. I'll keep you posted about any progress here 🙌

**Comment by henningmu** [comment] 2024-03-27 09:30
@dmitry-yudakov thank you for your patience, I'm happy to report that this is now fixed ✅

**Closed by henningmu** 2024-03-27 09:30 UTC
Labels: bug

**Comment by dmitry-yudakov** [comment] 2024-03-27 09:39
@henningmu Great, thanks! I can confirm it working 👍
